<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Desktop\ClinicManager.Win\ClinicManager.Win.csproj" />
  </ItemGroup>

  <ItemGroup>
  <PackageReference Include="ThisAssembly.Constants" />

  <PackageReference Include="System.Net.Http" />
  <PackageReference Include="System.Text.RegularExpressions" />
  <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />

  <PackageReference Include="Moq" />
  <PackageReference Include="xunit.v3" />
  <PackageReference Include="Shouldly" />

  <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
  <PackageReference Include="Humanizer.Core" />
  <PackageReference Include="NetArchTest.eNhancedEdition" />
</ItemGroup>
</Project>
