<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Constant Include="BuildInfo.ApplicationPath" Value="$(ArtifactsPath)\bin\ClinicManager.Win\debug\ClinicMgr.exe" />
  </ItemGroup>

  <ItemGroup>
  <PackageReference Include="ThisAssembly.Constants" />

  <PackageReference Include="System.Net.Http" />
  <PackageReference Include="System.Text.RegularExpressions" />

  <PackageReference Include="xunit.v3" />
  <PackageReference Include="Shouldly" />
  <PackageReference Include="FlaUI.Core.Signed" />
  <PackageReference Include="FlaUI.UIA3.Signed" />
  <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />

  <PackageReference Include="Humanizer.Core" />
</ItemGroup>
</Project>
