<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>ClinicMgr</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClinicManager\ClinicManager.csproj" />
  </ItemGroup>

    <ItemGroup>
    </ItemGroup>
</Project>
