<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>ClinicManager.Application.UnitTests</RootNamespace>
        <AssemblyName>ClinicManager.Application.UnitTests</AssemblyName>
    </PropertyGroup>

 

    <ItemGroup>
        <ProjectReference Include="..\..\Server\Application\Application.csproj" />
        <ProjectReference Include="..\..\Server\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>

</Project>
