<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>ClinicMgr</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
    <IncludePackageReferencesDuringMarkupCompilation>true</IncludePackageReferencesDuringMarkupCompilation>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClinicManager.Core\ClinicManager.Core.csproj" />
  </ItemGroup>

<ItemGroup>
    <PackageReference Include="DevExpress.Wpf.Scheduling" />
    <PackageReference Include="DevExpress.DataAccess" />
    <PackageReference Include="DevExpress.Document.Processor" />
    <PackageReference Include="DevExpress.Drawing.Skia" />
    <PackageReference Include="DevExpress.RichEdit.Export" />
    <PackageReference Include="DevExpress.Wpf.Accordion" />
    <PackageReference Include="DevExpress.Wpf.Carousel" />
    <PackageReference Include="DevExpress.Wpf.Charts" />
    <PackageReference Include="DevExpress.Wpf.Core.Extensions" />
    <PackageReference Include="DevExpress.Wpf.Dialogs" />
    <PackageReference Include="DevExpress.Wpf.Docking" />
    <PackageReference Include="DevExpress.Wpf.ExpressionEditor" />
    <PackageReference Include="DevExpress.Wpf.Gauges" />
    <PackageReference Include="DevExpress.Wpf.Grid" />
    <PackageReference Include="DevExpress.Wpf.LayoutControl" />
    <PackageReference Include="DevExpress.Wpf.Map" />
    <PackageReference Include="DevExpress.Wpf.NavBar" />
    <PackageReference Include="DevExpress.Wpf.PdfViewer" />
    <PackageReference Include="DevExpress.Wpf.PivotGrid" />
    <PackageReference Include="DevExpress.Wpf.Printing" />
    <PackageReference Include="DevExpress.Wpf.PrismAdapters" />
    <PackageReference Include="DevExpress.Wpf.PropertyGrid" />
    <PackageReference Include="DevExpress.Wpf.Ribbon" />
    <PackageReference Include="DevExpress.Wpf.RichEdit" />
    <PackageReference Include="DevExpress.Wpf.SchedulingReporting" />
    <PackageReference Include="DevExpress.Wpf.SpellChecker" />
    <PackageReference Include="DevExpress.Mvvm" />
    <PackageReference Include="DevExpress.Mvvm.CodeGenerators" />
    <PackageReference Include="DevExpress.Wpf.ThemesLW" />

    <PackageReference Include="Prism.Wpf" />
    <PackageReference Include="Prism.DryIoc" />

    <PackageReference Include="ThisAssembly.Constants" />
    <PackageReference Include="System.Text.Json" />

    <PackageReference Include="System.Net.Http" />
    <PackageReference Include="System.Text.RegularExpressions" />

  
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Xml" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />

    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="DryIoc.Microsoft.DependencyInjection" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="WPFLocalizeExtensionEzzFork" />
    <PackageReference Include="XAMLMarkupExtensionsEzzFork" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="MimeKit" />
    <PackageReference Include="Utf8StringInterpolation" />
    <PackageReference Include="Humanizer.Core" />

    <PackageReference Include="WpfAnalyzers" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" />
    <PackageReference Include="EnumerableAsyncProcessor" />
    <PackageReference Include="AsyncAwaitBestPractices" />
    <PackageReference Include="AsyncAwaitBestPractices.MVVM" />
    <PackageReference Include="AsyncKeyedLock" />
    <PackageReference Include="AsyncFixer" />

    <PackageReference Include="Ardalis.GuardClauses" />
  </ItemGroup>
</Project>
