<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>ClinicMgrPres</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Wpf" />
    <PackageReference Include="ThisAssembly.Constants" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="AsyncAwaitBestPractices.MVVM" />
    <PackageReference Include="AsyncFixer" />
    <PackageReference Include="WpfAnalyzers" />
</ItemGroup>

</Project>
