<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>ClinicMgrCr</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Wpf" />
    <PackageReference Include="ThisAssembly.Constants" />

    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Utf8StringInterpolation" />
    <PackageReference Include="Humanizer.Core" />
    <PackageReference Include="AsyncFixer" />
    <PackageReference Include="Ardalis.GuardClauses" />
  </ItemGroup>
</Project>
