<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>ClinicMgrMod</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ThisAssembly.Constants" />
    <PackageReference Include="Utf8StringInterpolation" />
    <PackageReference Include="Humanizer.Core" />
    <PackageReference Include="Ardalis.GuardClauses" />
  </ItemGroup>
</Project>
