name: Clinic WPF Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and UI Test
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          6.0.x
          8.0.x
          10.0.x
      
    - name: 'Cache: .nuke/temp, ~/.nuget/packages'
      uses: actions/cache@v4
      with:
        path: |
          .nuke/temp
          ~/.nuget/packages
        key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
         
    
    - name: Install wix (locked version)
      run: dotnet tool install --global wix --version 6.0.2
      
    - name: Install wix extesnion (locked version)
      run: wix.exe extension add -g WixToolset.UI.wixext/6.0.2

    - name: Run NUKE
      run: ./build.ps1

    - name: Create Test Report
      uses: icsharpcode/test-summary-action@dist
      if: always()
      with:
        paths: "artifacts/**/*.trx"
     

    # 6. Upload Artifacts
    # Uses 'if: always()' so logs are uploaded even if the build/test fails
    - name: Upload Build and Test Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-and-test-logs
        path: |
          Artifacts/Attachments/
        retention-days: 5
